<?php


// Détection et persistance de la langue
if (isset($_GET['lang']) && in_array($_GET['lang'], ['fr', 'en'])) {
    $_SESSION['lang'] = $_GET['lang'];
}
if (empty($_SESSION['lang'])) {
    $_SESSION['lang'] = 'fr'; // français par défaut
}
$lang = $_SESSION['lang'];


function __t(string $key): string {
    global $translations, $lang;
    return $translations[$lang][$key] ?? $key;
}

// Dictionnaire complet des traductions
$translations = [
    'fr' => [
        // Navigation & général
        'shop_name' => 'AO Shop',
        'home' => 'Accueil',
        'products' => 'Produits',
        'cart' => 'Panier',
        'profile' => 'Profil',
        'logout' => 'Déconnexion',
        'login' => 'Connexion',
        'register' => 'Inscription',
        'admin_panel' => 'Administration',
        'search' => 'Rechercher...',
        'balance' => 'Solde',
        'welcome' => 'Bienvenue',
        'back' => 'Retour',
        'save' => 'Enregistrer',
        'cancel' => 'Annuler',
        'delete' => 'Supprimer',
        'edit' => 'Modifier',
        'add' => 'Ajouter',
        'close' => 'Fermer',
        'confirm' => 'Confirmer',
        'yes' => 'Oui',
        'no' => 'Non',
        'all' => 'Tous',
        'price' => 'Prix',
        'quantity' => 'Quantité',
        'brand' => 'Marque',
        'reference' => 'Référence',
        'description' => 'Description',
        'category' => 'Catégorie',
        'available' => 'Disponible',
        'in_stock' => 'En stock',
        'out_of_stock' => 'Rupture de stock',
        'low_stock' => 'Stock faible',
        'actions' => 'Actions',
        'details' => 'Détails',

        // Auth
        'login_title' => 'Se connecter',
        'register_title' => 'S\'inscrire',
        'email' => 'Email',
        'password' => 'Mot de passe',
        'confirm_password' => 'Confirmer le mot de passe',
        'first_name' => 'Prénom',
        'last_name' => 'Nom',
        'no_account' => 'Pas encore de compte ?',
        'has_account' => 'Déjà un compte ?',
        'create_account' => 'Créer un compte',
        'login_btn' => 'Se connecter',
        'register_btn' => 'S\'inscrire',
        'password_mismatch' => 'Les mots de passe ne correspondent pas.',
        'invalid_credentials' => 'Email ou mot de passe incorrect.',
        'email_exists' => 'Cet email est déjà utilisé.',

        // Produits
        'add_to_cart' => 'Ajouter au panier',
        'buy_now' => 'Acheter maintenant',
        'best_sellers' => 'Meilleures ventes',
        'new_arrivals' => 'Nouveautés',
        'sort_by' => 'Trier par',
        'price_asc' => 'Prix croissant',
        'price_desc' => 'Prix décroissant',
        'brand_az' => 'Marque A-Z',
        'sales_desc' => 'Plus vendus',
        'grid_view' => 'Vue grille',
        'list_view' => 'Vue liste',
        'no_products' => 'Aucun produit trouvé.',

        // Comparaison
        'compare' => 'Comparer',
        'compare_this' => 'Comparer ce produit',
        'compare_products' => 'Comparaison de Produits',
        'back_to_products' => '← Retour aux produits',
        'selected_products' => 'produits sélectionnés',
        'compare_now' => 'Comparer maintenant →',
        'clear_all' => 'Vider',
        'max_compare' => 'Maximum 3 produits comparables à la fois.',
        'best_price' => 'Meilleur prix',
        'add_to_compare' => '+ Ajouter un produit à comparer',
        'same_category_only' => 'Vous pouvez uniquement comparer des produits de la même catégorie.',
        'min_compare' => 'Veuillez sélectionner au moins 2 produits à comparer.',
        'see_more' => 'Voir plus',
        'see_less' => 'Voir moins',

        // Panier
        'your_cart' => 'Votre panier',
        'empty_cart' => 'Votre panier est vide 🛒',
        'subtotal' => 'Sous-total',
        'total' => 'Total',
        'checkout' => 'Passer la commande',
        'remove' => 'Supprimer',
        'item_added' => 'Produit ajouté au panier ✓',
        'item_removed' => 'Produit retiré du panier',
        'order_placed' => 'Commande passée avec succès !',
        'cart_expired' => 'Certains articles ont expiré et ont été retirés.',

        // Solde
        'insufficient_balance' => 'Solde insuffisant pour cet achat.',
        'balance_empty' => 'Solde épuisé — Vous ne pouvez plus effectuer d\'achats.',
        'purchase_success' => 'Achat effectué avec succès !',

        // Abonnements
        'subscription' => 'Abonnement',
        'monthly_plan' => 'Mensuel',
        'yearly_plan' => 'Annuel',
        'monthly_price' => '29 DT / mois',
        'yearly_price' => '249 DT / an',
        'subscribe' => 'S\'abonner',
        'active_subscription' => 'Abonnement actif',
        'no_active_subscription' => 'Aucun abonnement actif',
        'subscription_success' => 'Abonnement souscrit avec succès !',
        'subscription_exists' => 'Vous avez déjà un abonnement actif.',
        'subscription_expires' => 'Expire le',
        'subscription_type' => 'Type d\'abonnement',

        // Roulette
        'daily_roulette' => 'Roulette du Jour',
        'spin' => 'Tourner',
        'free_spin' => 'Tour gratuit disponible',
        'paid_spin' => 'Tour payant (10 DT)',
        'spin_again' => 'Rejouer',
        'coupon_won' => 'Coupon gagné !',
        'your_coupon' => 'Votre coupon',
        'discount' => 'de réduction',
        'coupon_expires' => 'Expire dans',
        'hours' => 'heures',
        'minutes' => 'minutes',
        'seconds' => 'secondes',
        'already_spun' => 'Vous avez déjà tourné aujourd\'hui. Revenez demain !',
        'spin_cost' => 'Coût du tour',
        'no_free_spin' => 'Aucun tour gratuit disponible.',
        'free_spin_btn' => 'Tour gratuit',
        'paid_spin_btn' => 'Tourner pour 10 DT',
        'roulette_subtitle' => 'Tentez votre chance pour obtenir un coupon de réduction instantané.',
        'roulette_possible_rewards' => 'Réductions possibles',
        'roulette_active_coupon' => 'Coupon actif',
        'roulette_copy_code' => 'Copier le code',
        'roulette_code_copied' => 'Code coupon copié ✓',
        'roulette_spinning' => 'Tirage en cours...',
        'free_spin_note' => 'Votre tour gratuit est prêt. Bonne chance !',
        'paid_spin_note' => 'Le prochain tour coûte 10 DT et peut vous faire économiser bien plus.',

        // Profil
        'my_profile' => 'Mon profil',
        'my_orders' => 'Mes commandes',
        'member_since' => 'Membre depuis',
        'edit_profile' => 'Modifier le profil',

        // Admin
        'dashboard' => 'Tableau de bord',
        'total_revenue' => 'Revenu total',
        'total_orders' => 'Commandes totales',
        'total_clients' => 'Clients totaux',
        'best_product' => 'Meilleur produit',
        'worst_product' => 'Produit le moins vendu',
        'best_category' => 'Meilleure catégorie',
        'recent_orders' => 'Dernières commandes',
        'manage_products' => 'Gérer les produits',
        'manage_categories' => 'Gérer les catégories',
        'manage_stock' => 'Gérer le stock',
        'manage_accounts' => 'Gérer les comptes',
        'product_name' => 'Nom du produit',
        'product_added' => 'Produit ajouté avec succès.',
        'product_updated' => 'Produit modifié avec succès.',
        'product_deleted' => 'Produit supprimé avec succès.',
        'cannot_delete' => 'Impossible de supprimer : stock non nul.',
        'category_added' => 'Catégorie ajoutée avec succès.',
        'category_exists' => 'Cette catégorie existe déjà.',
        'photo' => 'Photo',

        // Footer
        'fast_delivery' => 'Livraison rapide',
        'delivery_text' => 'Livraison partout en Tunisie',
        'support_24_7' => 'Support 24/7',
        'support_text' => 'Toujours disponibles pour vous',
        'cash_on_delivery' => 'Paiement à la livraison',
        'cash_text' => 'Payez en toute sécurité',
        'fast_shipping' => 'Expédition rapide',
        'shipping_text' => 'Commandes traitées en 24h',
        'about' => 'À propos',
        'terms' => 'Conditions',
        'privacy' => 'Confidentialité',
        'returns' => 'Livraisons & Retours',
        'tracking' => 'Suivi',
        'pro_service' => 'Service pro',
        'sav' => 'SAV',
        'contact' => 'Contact',
        'order_tracking' => 'Suivi commandes',
        'address' => 'Sfax, Tunisie',
        'phone' => '+216 74 000 000',
        'email_contact' => 'contact@aoshop.tn',
        'shop_hours' => 'Lun–Sam: 8h00–20h00',
        'newsletter' => 'Newsletter',
        'newsletter_text' => 'Abonnez-vous pour recevoir nos offres exclusives.',
        'subscribe_btn' => 'S\'abonner',
        'copyright' => '© 2026 AO Shop. Tous droits réservés.',
    ],

    'en' => [
        // Navigation & general
        'shop_name' => 'AO Shop',
        'home' => 'Home',
        'products' => 'Products',
        'cart' => 'Cart',
        'profile' => 'Profile',
        'logout' => 'Logout',
        'login' => 'Login',
        'register' => 'Register',
        'admin_panel' => 'Admin Panel',
        'search' => 'Search...',
        'balance' => 'Balance',
        'welcome' => 'Welcome',
        'back' => 'Back',
        'save' => 'Save',
        'cancel' => 'Cancel',
        'delete' => 'Delete',
        'edit' => 'Edit',
        'add' => 'Add',
        'close' => 'Close',
        'confirm' => 'Confirm',
        'yes' => 'Yes',
        'no' => 'No',
        'all' => 'All',
        'price' => 'Price',
        'quantity' => 'Quantity',
        'brand' => 'Brand',
        'reference' => 'Reference',
        'description' => 'Description',
        'category' => 'Category',
        'available' => 'Available',
        'in_stock' => 'In stock',
        'out_of_stock' => 'Out of stock',
        'low_stock' => 'Low stock',
        'actions' => 'Actions',
        'details' => 'Details',

        // Auth
        'login_title' => 'Login',
        'register_title' => 'Register',
        'email' => 'Email',
        'password' => 'Password',
        'confirm_password' => 'Confirm Password',
        'first_name' => 'First Name',
        'last_name' => 'Last Name',
        'no_account' => 'No account yet?',
        'has_account' => 'Already have an account?',
        'create_account' => 'Create Account',
        'login_btn' => 'Login',
        'register_btn' => 'Register',
        'password_mismatch' => 'Passwords do not match.',
        'invalid_credentials' => 'Invalid email or password.',
        'email_exists' => 'This email is already in use.',

        // Products
        'add_to_cart' => 'Add to cart',
        'buy_now' => 'Buy now',
        'best_sellers' => 'Best Sellers',
        'new_arrivals' => 'New Arrivals',
        'sort_by' => 'Sort by',
        'price_asc' => 'Price: Low to High',
        'price_desc' => 'Price: High to Low',
        'brand_az' => 'Brand A-Z',
        'sales_desc' => 'Best Selling',
        'grid_view' => 'Grid view',
        'list_view' => 'List view',
        'no_products' => 'No products found.',

        // Comparison
        'compare' => 'Compare',
        'compare_this' => 'Compare this product',
        'compare_products' => 'Product Comparison',
        'back_to_products' => '← Back to products',
        'selected_products' => 'products selected',
        'compare_now' => 'Compare now →',
        'clear_all' => 'Clear all',
        'max_compare' => 'Maximum 3 products can be compared at once.',
        'best_price' => 'Best price',
        'add_to_compare' => '+ Add a product to compare',
        'same_category_only' => 'You can only compare products from the same category.',
        'min_compare' => 'Please select at least 2 products to compare.',
        'see_more' => 'See more',
        'see_less' => 'See less',

        // Cart
        'your_cart' => 'Your cart',
        'empty_cart' => 'Your cart is empty 🛒',
        'subtotal' => 'Subtotal',
        'total' => 'Total',
        'checkout' => 'Place order',
        'remove' => 'Remove',
        'item_added' => 'Product added to cart ✓',
        'item_removed' => 'Product removed from cart',
        'order_placed' => 'Order placed successfully!',
        'cart_expired' => 'Some items expired and were removed.',

        // Balance
        'insufficient_balance' => 'Insufficient balance for this purchase.',
        'balance_empty' => 'Balance exhausted — You can no longer make purchases.',
        'purchase_success' => 'Purchase completed successfully!',

        // Subscriptions
        'subscription' => 'Subscription',
        'monthly_plan' => 'Monthly',
        'yearly_plan' => 'Yearly',
        'monthly_price' => '29 DT / month',
        'yearly_price' => '249 DT / year',
        'subscribe' => 'Subscribe',
        'active_subscription' => 'Active subscription',
        'no_active_subscription' => 'No active subscription',
        'subscription_success' => 'Subscription successful!',
        'subscription_exists' => 'You already have an active subscription.',
        'subscription_expires' => 'Expires on',
        'subscription_type' => 'Subscription type',

        // Roulette
        'daily_roulette' => 'Daily Roulette',
        'spin' => 'Spin',
        'free_spin' => 'Free spin available',
        'paid_spin' => 'Paid spin (10 DT)',
        'spin_again' => 'Spin again',
        'coupon_won' => 'Coupon won!',
        'your_coupon' => 'Your coupon',
        'discount' => 'off',
        'coupon_expires' => 'Expires in',
        'hours' => 'hours',
        'minutes' => 'minutes',
        'seconds' => 'seconds',
        'already_spun' => 'You already spun today. Come back tomorrow!',
        'spin_cost' => 'Spin cost',
        'no_free_spin' => 'No free spin available.',
        'free_spin_btn' => 'Free Spin',
        'paid_spin_btn' => 'Spin for 10 DT',
        'roulette_subtitle' => 'Try your luck and win an instant discount coupon.',
        'roulette_possible_rewards' => 'Possible rewards',
        'roulette_active_coupon' => 'Active coupon',
        'roulette_copy_code' => 'Copy code',
        'roulette_code_copied' => 'Coupon code copied ✓',
        'roulette_spinning' => 'Spinning...',
        'free_spin_note' => 'Your free spin is ready. Good luck!',
        'paid_spin_note' => 'Next spin costs 10 DT and can save you much more.',

        // Profile
        'my_profile' => 'My Profile',
        'my_orders' => 'My Orders',
        'member_since' => 'Member since',
        'edit_profile' => 'Edit Profile',

        // Admin
        'dashboard' => 'Dashboard',
        'total_revenue' => 'Total Revenue',
        'total_orders' => 'Total Orders',
        'total_clients' => 'Total Clients',
        'best_product' => 'Best Selling Product',
        'worst_product' => 'Worst Selling Product',
        'best_category' => 'Best Category',
        'recent_orders' => 'Recent Orders',
        'manage_products' => 'Manage Products',
        'manage_categories' => 'Manage Categories',
        'manage_stock' => 'Manage Stock',
        'manage_accounts' => 'Manage Accounts',
        'product_name' => 'Product Name',
        'product_added' => 'Product added successfully.',
        'product_updated' => 'Product updated successfully.',
        'product_deleted' => 'Product deleted successfully.',
        'cannot_delete' => 'Cannot delete: stock is not zero.',
        'category_added' => 'Category added successfully.',
        'category_exists' => 'This category already exists.',
        'photo' => 'Photo',

        // Footer
        'fast_delivery' => 'Fast Delivery',
        'delivery_text' => 'Delivery everywhere in Tunisia',
        'support_24_7' => 'Support 24/7',
        'support_text' => 'Always here for you',
        'cash_on_delivery' => 'Cash on Delivery',
        'cash_text' => 'Pay securely',
        'fast_shipping' => 'Fast Shipping',
        'shipping_text' => 'Orders processed in 24h',
        'about' => 'About',
        'terms' => 'Terms',
        'privacy' => 'Privacy',
        'returns' => 'Delivery & Returns',
        'tracking' => 'Tracking',
        'pro_service' => 'Pro Service',
        'sav' => 'After-sales',
        'contact' => 'Contact',
        'order_tracking' => 'Order Tracking',
        'address' => 'Sfax, Tunisia',
        'phone' => '+216 74 000 000',
        'email_contact' => 'contact@aoshop.tn',
        'shop_hours' => 'Mon–Sat: 8:00 AM–8:00 PM',
        'newsletter' => 'Newsletter',
        'newsletter_text' => 'Subscribe to receive our exclusive offers.',
        'subscribe_btn' => 'Subscribe',
        'copyright' => '© 2026 AO Shop. All rights reserved.',
    ],
];
